# ------------------------------------------------------------------------------
# Make file for Chapter 09: Process Credentials
# ------------------------------------------------------------------------------

.PHONY : all
all : my_initgroups

my_initgroups: my_initgroups.c
	gcc -o my_initgroups my_initgroups.c
