# ------------------------------------------------------------------------------
# Make file for Chapter 04: File I/O: The Universal I/O Model
# ------------------------------------------------------------------------------

.PHONY : all
all : tee cp

cp : cp.c
	gcc -o cp cp.c

tee : tee.c
	gcc -o tee tee.c
