# ------------------------------------------------------------------------------
# Make file for Chapter 04: File I/O: The Universal I/O Model
# ------------------------------------------------------------------------------

.PHONY : all
all : tee

tee : tee.c
	gcc -o tee tee.c
