# ------------------------------------------------------------------------------
# Make file for Chapter 08: Users and Groups
# ------------------------------------------------------------------------------

.PHONY : all
all : my_getpwnam

my_getpwnam: my_getpwnam.c
	gcc -o my_getpwnam my_getpwnam.c

