# ------------------------------------------------------------------------------
# Make file for Chapter 07: Memory Allocation
# ------------------------------------------------------------------------------

.PHONY : all
all : free_and_sbrk

free_and_sbrk: free_and_sbrk.c
	gcc -o free_and_sbrk -I ../03_System_Programming_Concepts/ free_and_sbrk.c ../03_System_Programming_Concepts/error_functions.c ../03_System_Programming_Concepts/get_num.c

