# ------------------------------------------------------------------------------
# Make file for Chapter 06: Processes
# ------------------------------------------------------------------------------

.PHONY : all
all : mem_segments

mem_segments: mem_segments.c
	gcc -o mem_segments -I ../03_System_Programming_Concepts/ mem_segments.c ../03_System_Programming_Concepts/error_functions.c
