# ------------------------------------------------------------------------------
# Make file for Chapter 13: File I/O Buffering
# ------------------------------------------------------------------------------

.PHONY : all
all : ex13_1 ex13_2 ex13_3 ex13_4 ex13_5

ex13_1: ex13_1.c
	gcc -o ex13_1 ex13_1.c

ex13_2: ex13_2.c
	gcc -o ex13_2 ex13_2.c

ex13_3: ex13_3.c
	gcc -o ex13_3 ex13_3.c

ex13_4: ex13_4.c
	gcc -o ex13_4 ex13_4.c

ex13_5: ex13_5.c
	gcc -o ex13_5 ex13_5.c
